name: CI

on: [push, pull_request]

permissions:
  contents: read
  id-token: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: 'Install Hatch'
        uses: pypa/hatch@install
      - name: 'Run static analysis'
        run: hatch fmt --check
      - name: 'Run tests'
        run: hatch test
